spring.application.name=event-registering

spring.application.version=${project.version}

spring.data.mongodb.uri=${MONGO_DB_URI}
spring.data.mongodb.database=${DB_NAME}
spring.data.mongodb.username=${DB_USER}
spring.data.mongodb.password=${DB_PASS}

spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER}
spring.rabbitmq.password=${RABBIT_PASS}

messaging.notifications.topic-name=notifications
messaging.notifications.queue-name=notifications
messaging.notifications.channel-name=channel:notifications
messaging.notifications-logs.queue-name=logs
messaging.notifications-logs.channel-name=channel:logs
